# Generated by Django 3.2.9 on 2021-12-06 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_user_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produits',
            old_name='type',
            new_name='type_produit',
        ),
    ]
