# Generated by Django 3.2.9 on 2021-12-07 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_rename_type_produits_type_produit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
